@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.dhyces.ambientplayers.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;